### ISSUE TITLE
Configurable consistency levels

### ISSUE THREAD

**Issue by ajs6f** [ajs6f/trellis-cassandra#23]
Consistency levels for write and read operations to Cassandra can be configured on a per-statement basis. This ticket has two parts. After the first, a globally-constant consistency level can be configured for read and for write statements-- two settings in all. After the second, a programmatic policy can be deployed to determine on a case-by-case basis what consistency to provide for statements.

**Comment by ajs6f** [comment]
@gregjan You're going to want to put an eye on this as we get into testing. The default consistency for reading and writing is `ONE`, which is probably not crazy for a lot of use cases, but we may want to see how things behave with different settings.

**Comment by gregjan** [comment]
Yes, this presents us with some distinct testing choices, which ideally I think would be paired with the replication factor. Is that a configurable item at this point?

**Comment by ajs6f** [comment]
No, it's completely outside the control of the software (which I should document). The idea is that `trellis-cassandra` takes no responsibility for your C* cluster. We give you a minimal schema. You decide how to set up and manage your cluster. If you're not up to that task... you probably shouldn't be investing in a repository technology that is entirely dependent on you maintaining a C* cluster.

**Comment by ajs6f** [comment]
TBC (because my previous comment my be confusing), replication, unlike consistency, isn't a client-side choice for Cassandra. It's set when the table is created or altered. Consistency can vary down to the individual statement, under client control.
