### ISSUE TITLE
Binary "contains" query 

### ISSUE THREAD

**Issue by ajs6f** [ajs6f/trellis-cassandra#4]
@gregjan, question for you--

The current query for checking whether a binary exists is:

`SELECT identifier FROM Binarydata WHERE identifier = ? and chunk_index = 0;`

Am I right in thinking that the `and chunk_index = 0` is unnecessary and be removed? If there is any chunk, even if it isn't the first, we can answer the question with a "yes, this binary exists". Right?

**Comment by gregjan** [comment]
It's true. That query was hoping to be optimized to not fetch more than one. Some kind of boolean function that doesn't count everything might be faster..

**Comment by gregjan** [comment]
That should work! I like it.

**Comment by ajs6f** [comment]
Turns out that @acoburn ended up removing `contains` from the API, so we needn't support it with any query at all. Occam's Razor FTW!
